services:
  app:
    container_name: backend
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      DATABASE_NAME: dev-test-db
      DATABASE_USER: test_user_name
      DATABASE_PASS: test_pass
      DATABASE_URI: mongodb://database:27017
      JWT_SECRET: test-secret
    ports:
      - '4000:4000'
    depends_on:
      - database

  # start the mongodb service as container
  database:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: test_user_name
      MONGO_INITDB_ROOT_PASSWORD: test_pass